from enum import Enum


class Limits(Enum):
    MIN_PASSWORD_LENGTH = 3
    JWT_TOKEN_LIFETIME = 3600

    CHARITY_BASE_NAME_MIN_LEN = 1
    CHARITY_BASE_NAME_MAX_LEN = 100
    CHARITY_BASE_DES_MIN_LEN = 1

    CHARITY_CREATE_NAME_MIN_LEN = 1
    CHARITY_CREATE_NAME_MAX_LEN = 100
    CHARITY_CREATE_DES_MIN_LEN = 1

    ROW_COUNT = 100
    COLUMN_COUNT = 11

    LIMIT = 10
    OFFSET = 0


class Constants(object):
    FORMAT = "%Y/%m/%d %H:%M:%S"
